server:
 servlet:
    context-path: /produdoro/api
    
spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://arianepinheiro:gMiFGD3IKzuqrTV0@wakanda.kasf1.mongodb.net/wakanda?retryWrites=true&w=majority&appName=wakanda}
      auto-index-creation: true      

springdoc:
  swagger-ui:
    path: /public/swagger

 
produdoro:
  jwt:
    expiracao: ${JWT_TEMPO_EXPIRACAO:15}
    chave: ${JWT_CHAVE:123456}